Repository at-aaims/HPG-MxP, pull requests merged in 2025-07, with the labels that each got.

#3 ROCTX and NVTX profiling annotations
  CMakeLists.txt
  src/BenchGMRES.cpp
  src/ComputeDotProduct_blas.cpp
  src/ComputeDotProduct_gpu.cpp
  src/ComputeDotProduct_ref.cpp
  src/ComputeGEMMT_gpu.cpp
  src/ComputeGEMMT_ref.cpp
  src/ComputeGEMVT_blas.cpp
  src/ComputeGEMVT_gpu.cpp
  src/ComputeGEMVT_ref.cpp
  src/ComputeGEMV_blas.cpp
  src/ComputeGEMV_gpu.cpp
  src/ComputeGEMV_ref.cpp
  src/ComputeGS_Forward_gpu.cpp
  src/ComputeGS_Forward_ref.cpp
  src/ComputeMG.cpp
  src/ComputeMG_ref.cpp
  src/ComputeSPMV_gpu.cpp
  src/ComputeSPMV_ref.cpp
  src/ComputeWAXPBY_opt.dev.cpp
  src/ComputeWAXPBY_ref.cpp
  src/ExchangeHalo_gpu.cpp
  src/ExchangeHalo_ref.cpp
  src/GMRES.cpp
  src/GMRES_IR.cpp
  src/Profiling.hpp
  src/Vector.dev.cpp
  src/ell_matrix.cpp
  src/hpgmp.hpp
  src/main_hpgmp.cpp
  src/mytimer.hpp
Labels: enhancement, perf_analysis

#4 Script for stacked bar plot
  tools/plot_stacked_breakdown.py
Labels: documentation

#5 Fix bugs and remove obsolete documentation and setup
  AUTHORS
  BUGS
  COPYRIGHT
  ChangeLog
  INSTALL
  Makefile
  Makefile.ext
  README
  README.md
  TODO
  bin/hpgmp.dat
  configure
  doc/install.md
  doc/run.md
  index.doc
  setup/Make.GCC_OMP
  setup/Make.ICPC_OMP
  setup/Make.Linux_MPI
  setup/Make.Linux_Serial
  setup/Make.MPIICPC_OMP
  setup/Make.MPI_CRAY_Crusher
  setup/Make.MPI_CRAY_Serial
  setup/Make.MPI_GCC_CUDA
  setup/Make.MPI_GCC_OMP
  setup/Make.MPI_HIP_Serial
  setup/Make.MPI_ICPC
  setup/Make.MPI_ICPC_OMP
  setup/Make.Mac_MPI
  setup/Make.Mac_Serial
  setup/Make.Mac_Serial_debug
  setup/Make.UNKNOWN
  src/ComputeMG.cpp
  src/perf_counter.hpp
  tools/hpcg.astyle
  tools/hpcg.dox
  tools/hpcg1.css
  tools/makefile.py
  tools/updateDoxWeb
  tools/updateTarfile
  unittesting/multicoloring.cpp
  web/doc/HPCG-Benchmark.docx
  web/doc/HPCG-Benchmark.pdf
  web/doc/HPCG-Logo.jpg
  web/doc/HPCG-Logo.pptx
  web/doc/HPCG-Logo.tiff
  web/doc/HPCG-Specification.docx
  web/doc/HPCG-Specification.pdf
  web/doc/HPCG-workflow.pptx
  web/doc/HPCG-workflow.tiff
  web/doc/HPG-MxP-Slides.pdf
Labels: bug, documentation

#6 Add run modes to include standalone runs for performance analysis
  CMakeLists.txt
  README.md
  doc/run.md
  src/BenchGMRES.cpp
  src/BenchGMRES.hpp
  src/GMRES.cpp
  src/GMRES.hpp
  src/GMRESData.hpp
  src/GMRES_IR.cpp
  src/GMRES_IR.hpp
  src/ReportResults.cpp
  src/ReportResults.hpp
  src/SetupProblem.cpp
  src/SetupProblem.hpp
  src/TestGMRES.cpp
  src/TestGMRES.hpp
  src/ValidGMRES.cpp
  src/ValidGMRES.hpp
  src/estimate_run_time.cpp
  src/estimate_run_time.hpp
  src/hpgmp.hpp
  src/init.cpp
  src/main_hpgmp.cpp
  src/main_time.cpp
  src/options_strings.cpp
  unittesting/dot.cpp
  unittesting/gs_multicolor.cpp
  unittesting/test_spmv.cpp
Labels: enhancement
